# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    initrd.kernelModules = ["i2c_hid_acpi" "i2c_hid" "hid_multitouch"];
    initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    loader = {
      efi.canTouchEfiVariables = true;
      systemd-boot.enable = true;
    };
    extraModulePackages = [ ];
    kernelModules = [ "kvm-intel" ];

    plymouth = {
      enable = true;
      theme = "connect";

      themePackages = [
        (pkgs.stdenv.mkDerivation {
          pname = "plymouth-theme-connect";
          version = "1.0";
          src = pkgs.fetchFromGitHub {
            owner = "adi1090x";
            repo = "plymouth-themes";
            rev = "bf2f570bee8e84c5c20caac353cbe1d811a4745f";
            sha256 = "sha256-VNGvA8ujwjpC2rTVZKrXni2GjfiZk7AgAn4ZB4Baj2k=";
          };
          installPhase = ''
            mkdir -p $out/share/plymouth/themes/connect
            cp -r pack_1/connect/* $out/share/plymouth/themes/connect/
            
            # Fix hardcoded paths in .plymouth file
            substituteInPlace $out/share/plymouth/themes/connect/connect.plymouth \
              --replace "/usr/share/plymouth/themes/connect" "$out/share/plymouth/themes/connect"
          '';
        })
      ];
    };
    consoleLogLevel = 3;
    initrd.verbose = false;
    kernelParams = [
      "quiet"
      "splash"
      "boot.shell_on_fail"             # полезно — если что-то сломается, дропнет в shell
      "rd.systemd.show_status=auto"    # или false / error
      "udev.log_priority=3"
      "loglevel=3"
      # "plymouth.enable=1"           # обычно не нужно, nixos сам ставит
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/19025fd7-83cb-4ca5-8d7a-14e1fb76b2ac";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CE76-41CB";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
