#!/usr/bin/env bash

notes_dir=$HOME/notes/
obsidian_dir=$HOME/Obsidian/shining/
TERMINAL=alacritty


newnote () { \
  dir="$(command ls -d "$notes_dir" "$obsidian_dir" 2>/dev/null | fuzzel --dmenu -l 5 -p 'Choose directory: ')" || exit 0
  : "${dir:=$notes_dir}"
  name="$(echo "" | fuzzel --dmenu -p "Enter a name: ")" || exit 0
  : "${name:=$(date +%F_%H-%M-%S)}"
  setsid -f "$TERMINAL" -e vim "$dir$name.md" >/dev/null 2>&1
}

selected () { \
  choice=$(
    echo -e "New\n$(find $notes_dir -type f -printf '%T@ %P\n' | sort -nr | cut -d' ' -f2-)" | fuzzel --dmenu -l 5 -p "Note: "
  )
  case $choice in
    New) newnote ;;
    *.md) setsid -f "$TERMINAL" -e vim "$notes_dir$choice" >/dev/null 2>&1 ;;
    *) exit ;;
  esac
}

selected
